### ISSUE TITLE
Uncached result order

### ISSUE THREAD

**Issue by Blissingg** [Zaarrg/comet-uncached#9]
I might be missing something in the todo or maybe its not fully implemented yet but no matter which combination of sorting I try the order for uncached links always seem to rigidly stay sorted by highest seeders first.

Is this the intended behavior? Or are there plans to implement sorting for uncached results similar to how Mediafusion can still give sort and give info about uncached results?

**Comment by g0ldyy** [comment]
you are not supposed to start using rewrite now lmao

**Comment by Blissingg** [comment]
> you are not supposed to start using rewrite now lmao

Oh so you don’t want people to test it or give feedback then? Good attitude LmAo

**Comment by g0ldyy** [comment]
> > you are not supposed to start using rewrite now lmao
> 
> Oh so you don’t want people to test it or give feedback then? Good attitude LmAo

mb I thought you opened this issue on the official comet repo and was complaining about the uncached rewrite that is not finished yet 💀

**Comment by Zaarrg** [comment]
@Blissingg 
What settings did u exactly use ? 
Also did you have Uncached selected under the Resolutions setting.
And where the links from torrentio or jackett/prowlarr?
And did the links show size and seeders in stremio?

Because it is intended that the uncached links still follow the Result Sorting selected. 
Meaning if you have Sort by Resolution then Rank, It should be sorted by that not seeders not matter if uncached or not. 

Only exception is with uncached links that have missing data like missing seeders or size. Those will be while sorting ignored and sorted to the bottom and everything that can be sorted to the top. 

(Also the missing data cant really be fixed as we only know the size or seeders when u click on the link and it starts the caching to debrid. )

And thanks for reporting as this allows me to make the fork even better and bug proof. 

Edit:

Okay tested myself and it is indeed bugged. When u have Uncached selected under Resolutions the Result Sorting will not work as in the early stages when i implemented just basic sorting i decided to always sort everything in the Resolution "Uncached" by seeders as the links with most seeders should be the one which download the fastest in case of uncached links.

Will patch this today or tomorrow. 

So that the stuff in the "Uncached" Resolution will still follow the main sorting selected as Results Sorting in the config and probably add a additional config option to force sort the "Uncached" Resolution by seeders, rank or size so that both cached and uncached can have different sorting.

For now if you wanted it fixed deselect "Uncached" in the Resolution tab on the config page.

**Comment by Blissingg** [comment]
> @Blissingg What settings did u exactly use ? Also did you have Uncached selected under the Resolutions setting. And where the links from torrentio or jackett/prowlarr? And did the links show size and seeders in stremio?
> 
> Because it is intended that the uncached links still follow the Result Sorting selected. Meaning if you have Sort by Resolution then Rank, It should be sorted by that not seeders not matter if uncached or not.
> 
> Only exception is with uncached links that have missing data like missing seeders or size. Those will be while sorting ignored and sorted to the bottom and everything that can be sorted to the top.
> 
> (Also the missing data cant really be fixed as we only know the size or seeders when u click on the link and it starts the caching to debrid. )
> 
> And thanks for reporting as this allows me to make the fork even better and bug proof.
> 
> Edit:
> 
> Okay tested myself and it is indeed bugged. When u have Uncached selected under Resolutions the Result Sorting will not work as in the early stages when i implemented just basic sorting i decided to always sort everything in the Resolution "Uncached" by seeders as the links with most seeders should be the one which download the fastest in case of uncached links.
> 
> Will patch this today or tomorrow.
> 
> So that the stuff in the "Uncached" Resolution will still follow the main sorting selected as Results Sorting in the config and probably add a additional config option to force sort the "Uncached" Resolution by seeders, rank or size so that both cached and uncached can have different sorting.
> 
> For now if you wanted it fixed deselect "Uncached" in the Resolution tab on the config page.

Sorry just tested now and yeah its like you said if you have uncached selected in resoloution it won't sort properly. Removing this fixed the issue. I was using Jackett.

**Comment by Zaarrg** [comment]
Fixed in the latest commit.
Fix should be present after updating / repulling ur docker image.
Thanks for reporting!
